CREATE TABLE env (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

CREATE TABLE flags (
  id SERIAL PRIMARY KEY,
  env_id INT,
  key TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  enabled BOOLEAN NOT NULL DEFAULT false,
  rollout INT NOT NULL DEFAULT 0 CHECK(rollout BETWEEN 0 AND 100),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(env_id, key),
  FOREIGN KEY (env_id) REFERENCES env(id) ON DELETE CASCADE
);